src/main/java/com/grepp/coffee/service/menu/MenuService.java, src/main/java/com/grepp/coffee/service/menu/MenuServiceImpl.java, src/main/java/com/grepp/coffee/service/order/OrderService.java, src/main/java/com/grepp/coffee/service/order/OrderServiceImpl.java
Service 구현을 위한 인터페이스 작성
아직 매서드가 실제로 구현되지 않음
=> feat: Add Service Interface

src/main/java/com/grepp/coffee/app/model/dto/CoffeeDto.java, src/main/java/com/grepp/coffee/app/model/dto/DetailedOrderDto.java, src/main/java/com/grepp/coffee/app/model/dto/OrderDto.java, src/main/java/com/grepp/coffee/app/model/entity/Coffee.java, src/main/java/com/grepp/coffee/service/menu/MenuService.java, src/main/java/com/grepp/coffee/service/menu/MenuServiceImpl.java, src/main/java/com/grepp/coffee/service/order/OrderService.java, src/main/java/com/grepp/coffee/service/order/OrderServiceImpl.java
- Service 구현을 위한 인터페이스 작성 및 Dto의 패키지 구조 변경
- CoffeeDto에 누락된 Name 필드 작성
=> Service & Dto

src/main/java/com/grepp/coffee/app/service/MenuService.java, src/main/java/com/grepp/coffee/app/service/OrderService.java
- MenuServiceImpl -> MenuService 로 클래스명 변경되었습니다.
- OrderServiceImpl -> OrderService 로 클래스명 변경되었습니다.
- OrderService의 매서드들에 임시적인 리턴값이 지정되었습니다.
=> Temporary return Value in OrderService

src/main/java/com/grepp/coffee/app/model/auth/AuthService.java, src/main/java/com/grepp/coffee/app/model/auth/code/Role.java, src/main/java/com/grepp/coffee/app/model/auth/domain/Principal.java
=> ::sparkles:: add Auth pakage

src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/java/com/grepp/coffee/infra/response/ApiResponse.java, src/main/java/com/grepp/coffee/infra/response/ResponseCode.java, src/main/resources/application.properties, src/main/webapp/WEB-INF/web.xml
Config 파일 속 Securityfile 만들어놨습니다. 
infra안에 response, auth 폴더 옮겨 놓았습니다.
=> ::sparkles:: add SecurityConfig, auth, response

src/main/java/com/grepp/coffee/app/model/repository/CoffeeRepository.java, src/main/java/com/grepp/coffee/app/model/repository/mapper/CoffeeMapper.java, src/main/java/com/grepp/coffee/app/model/repository/mapper/OrderMapper.java, src/main/resources/mybatis.mappers/coffeeMapper.xml, src/main/resources/mybatis.mappers/orderMapper.xml
ADD Coffee(Menu)
CoffeeMapper Interface
coffeeMapper xml
CoffeeRepository Class
구현
메뉴 CRUD가 급한 것 같아 간단하게 만들었습니다.
추가적으로 구현한 부분이 있다면 말씀해주세요.
=> :sparkles: feat: ADD Coffee(Menu)

src/main/java/com/grepp/coffee/app/service/MenuService.java
- 메뉴 추가, 조회, 수정, 삭제에 대한 로직을 추가했습니다.
=> :sparkles: Add logic for MenuService

src/main/java/com/grepp/coffee/app/model/repository/OrderRepository.java, src/main/java/com/grepp/coffee/app/model/repository/mapper/OrderMapper.java
Update Order Repository, Mapper
OrderMapper : 리턴 타입 수정
Order Repository : 리턴 타입 수정 및 리턴 값 설정
서비스 단에서 요청한 리턴 타입 수정 건을 처리하였습니다.
잘 작동되는 지 확인 부탁드립니다.
=> :bug: fix: Update Order Repository, Mapper

src/main/java/com/grepp/coffee/app/service/OrderService.java
- 주문 확정, 취소, 정보열람에 대한 처리를 완료하였습니다.
=> :sparkles: Add logic for OrderService

src/main/java/com/grepp/coffee/app/controller/api/member/MemberApiController.java, src/main/java/com/grepp/coffee/app/controller/api/order/OrderApiController.java, src/main/java/com/grepp/coffee/app/controller/api/order/payload/ApiRequestPayload.java, src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/SigninRequest.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/SignupRequest.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/java/com/grepp/coffee/app/controller/web/order/payload/OrderRequest.java, src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/member/mypage.jsp, src/main/webapp/WEB-INF/view/member/signin.jsp, src/main/webapp/WEB-INF/view/member/signup.jsp
member controller를 추가하며 signin, signup, mypage를 만들었습니다.
또한 security도 변경하여 문제없이 접근하실 수 있을 겁니다.
=> signin, signup 기능 추가

src/main/java/com/grepp/coffee/app/model/repository/MemberRepository.java, src/main/resources/mybatis.mappers/coffeeMapper.xml, src/main/resources/mybatis.mappers/memberMapper.xml, src/test/java/com/grepp/coffee/app/model/repository/CoffeeRepositoryTest.java
Update memberMapper.xml
enabled에 기본값으로 true가 들어가지 않아 발생한 오류 수정
이제 잘 들어갈겁니다.
=> :bug: fix: Update memberMapper.xml

src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/include/header.jsp, src/main/webapp/WEB-INF/view/include/page.jsp, src/main/webapp/WEB-INF/view/member/mypage.jsp
로그인 시 헤더에 뜨는 버튼이 달라집니다.
로그인 시 헤더에 마이 페이지와 로그아웃이 뜨도록 바꾸었습니다.
로그인 시 헤더에 마이 페이지와 로그아웃이 뜨도록 바꾸었습니다.
회원 가입 시에 이메일 형식이 아니어도 사용 가능한 아이디라고 뜨는 거 곧 고치겠습니다
그리고 rememberme 추가해야됨
=> :bug: fix header, signin

src/main/resources/mybatis.mappers/orderMapper.xml, src/test/java/com/grepp/coffee/app/model/repository/CoffeeRepositoryTest.java
Update orderMapper.xml
orderMapper.xml에 parameterType이 String으로 잡혀있어 우편번호를 처리 못하던 버그를 수정하였습니다.
이제 되는 지 확인 부탁드립니다
=> :bug: fix: Update orderMapper.xml

src/main/java/com/grepp/coffee/app/controller/api/admin/AdminApiController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/payload/CoffeeRegistRequest.java, src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/admin/adminpage.jsp, src/main/webapp/WEB-INF/view/admin/menu-list.jsp, src/main/webapp/WEB-INF/view/admin/menu-regist.jsp, src/main/webapp/WEB-INF/view/admin/menu-update.jsp, src/main/webapp/WEB-INF/view/include/header.jsp, src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/menu-btn.js
관리자 페이지와 관리자가 커피 메뉴를 관리하는 기능이 추가되었습니다.
jsp들 추가하였습니다
또한 menu 컨트롤도 추가하여 기능 사용 가능합니다.
=> admin 페이지, menu 관리 페이지 추가

src/main/java/com/grepp/coffee/app/model/repository/CoffeeRepository.java
- TODO 주석과, 필요한 예상 매서드의 기본형을 작성해 두었습니다.
=> :bulb: Add TODO comments

src/main/java/com/grepp/coffee/app/model/admin/AdminRepository.java, src/main/java/com/grepp/coffee/app/model/admin/AdminService.java
- 관리자의 주문 관리를 위한 임시 클래스 파일들을 추가하였습니다.
=> :construction: New classes for admin to manage orders

src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/SignupRequest.java, src/main/java/com/grepp/coffee/app/model/auth/AuthService.java, src/main/java/com/grepp/coffee/app/model/auth/domain/Principal.java, src/main/java/com/grepp/coffee/app/model/member/MemberRepository.java, src/main/java/com/grepp/coffee/app/model/member/MemberService.java, src/main/java/com/grepp/coffee/app/model/member/dto/MemberDto.java, src/main/java/com/grepp/coffee/app/model/member/dto/PrincipalDto.java, src/main/java/com/grepp/coffee/app/model/member/mapper/MemberMapper.java, src/main/resources/mybatis.mappers/memberMapper.xml
Member와 관련된 dto, service 등의 파일들을 member 패키지로 이동하였습니다.
=> :truck: Move Member related classes into member package

src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/java/com/grepp/coffee/app/controller/web/order/payload/OrderRequest.java, src/main/java/com/grepp/coffee/app/model/admin/ManageOrderRepository.java, src/main/java/com/grepp/coffee/app/model/admin/ManageOrderService.java, src/main/java/com/grepp/coffee/app/model/member/MemberRepository.java, src/main/java/com/grepp/coffee/app/model/member/MemberService.java, src/main/java/com/grepp/coffee/app/model/member/mapper/MemberMapper.java, src/main/java/com/grepp/coffee/app/model/order/OrderRepository.java, src/main/java/com/grepp/coffee/app/model/order/OrderService.java, src/main/java/com/grepp/coffee/app/model/order/dto/DetailedOrderDto.java, src/main/java/com/grepp/coffee/app/model/order/dto/MyPageOrderDto.java, src/main/java/com/grepp/coffee/app/model/order/dto/OrderDto.java, src/main/java/com/grepp/coffee/app/model/order/mapper/OrderMapper.java, src/main/java/com/grepp/coffee/app/model/repository/mapper/DetailedOrderMapper.java, src/main/resources/mybatis.mappers/memberMapper.xml, src/main/resources/mybatis.mappers/orderMapper.xml
order과 관련된 파일들을 order패키지로 이동하고, 마이페이지의 주문내역 확인을 위한 매서드를 추가했습니다.
사용되지 않는 하나의 Mapper파일을 삭제하였습니다.
이메일과 주소를 받아와 고객정보를 업데이트 하는 매서드를 추가했습니다.
=> :recycle: Refactor and new features

src/main/java/com/grepp/coffee/app/controller/api/admin/AdminApiController.java, src/main/java/com/grepp/coffee/app/controller/api/order/OrderApiController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/payload/CoffeeRegistRequest.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeRepository.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeService.java, src/main/java/com/grepp/coffee/app/model/coffee/code/CoffeeImgType.java, src/main/java/com/grepp/coffee/app/model/coffee/dto/CoffeeDto.java, src/main/java/com/grepp/coffee/app/model/coffee/dto/CoffeeImgDto.java, src/main/java/com/grepp/coffee/app/model/coffee/mapper/CoffeeMapper.java, src/main/resources/mybatis.mappers/coffeeMapper.xml, src/test/java/com/grepp/coffee/app/model/repository/CoffeeRepositoryTest.java
- 커피 메뉴와 관련된 파일들을 coffee package로 이동시켰습니다.
=> :truck: Move coffee menu related files into coffee package

src/main/java/com/grepp/coffee/app/controller/api/admin/AdminApiController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/UpdateAddressRequest.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/admin/menu-update.jsp, src/main/webapp/WEB-INF/view/admin/order-list.jsp, src/main/webapp/WEB-INF/view/member/mypage.jsp, src/main/webapp/WEB-INF/view/member/update-address.jsp, src/main/webapp/assets/js/manage-order.js
관리자 페이지의 주문 관리 기능과 멤버의 마이페이지를 구현하였습니다.
=> admin/order, mypage 구현 완료

src/main/java/com/grepp/coffee/app/model/coffee/CoffeeRepository.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeService.java
커피 메뉴 관리 시 커피 사진도 같이 관리 할 수 있도록 매소드를 수정했습니다.
=> :sparkles: Add, Get, Update, Delete Coffee with image

src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/member/signin.jsp
로그인한 정보를 기억합니다.
시큐리티에 rememer me를 추가하여 로그인한 사용자를 기억합니다.
=> :sparkles: add rememberme

src/main/webapp/WEB-INF/view/include/footer.jsp, src/main/webapp/WEB-INF/view/include/header.jsp, src/main/webapp/WEB-INF/view/order/order.jsp
=> :lipstick: Change UI of order page

src/main/java/com/grepp/coffee/app/model/coffee/CoffeeRepository.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeService.java
- 메뉴 추가, 수정시 필요한 파라매터를 변경하고 이미지를 처리하는 로직을 개선하였습니다.
=> :recycle: Change parameter of add/update menu methods

src/main/java/com/grepp/coffee/app/controller/api/order/OrderApiController.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/webapp/WEB-INF/view/member/signup.jsp, src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/count.js
validation의 결과를 signup페이지에서 보이고 order에서 stock을 고려하도록 하였습니다.
signup에서 validation에 걸린 요소가 있다면 사용자에게 이를 알릴 수 있는 텍스트를 출력합니다.
주문 시에 재고를 보여주고, 그 이상 담는 다면 재고가 없다는 알림을 띄웁니다.
또한 구매하기를 누를 때 payment와 연결하도록 하였습니다.
=> order 및 jsp 수정

src/main/resources/mybatis.mappers/coffeeMapper.xml
- 커피메뉴 추가시 이미지가 추가될때 coffeeId=null로 넘어오는 문제를 해결했습니다.
=> :ambulance: Fix an error that occurred when inserting a new coffee menu.

src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/model/auth/code/Role.java, src/main/java/com/grepp/coffee/app/model/member/MemberService.java, src/main/webapp/WEB-INF/view/include/header.jsp
=> :recycle: Rename role enum types

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java
=> security 수정

src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/model/auth/code/Role.java, src/main/java/com/grepp/coffee/app/model/member/MemberService.java, src/main/webapp/WEB-INF/view/include/header.jsp
=> :ambulance: Rollback role enum types

src/main/java/com/grepp/coffee/infra/util/file/FileUtil.java, src/main/resources/application.properties
- 파일 저장 위치가 절대경로로 되어있어, 각자의 로컬에서 프로젝트 실행시 저장이 안될수도 있는 문제를 해결했습니다.
- 프로젝트의 루트위치에 파일이 저장되도록 수정했습니다.
=> :recycle: Refactor FileUtil to upload images to project's root path

src/main/resources/init/data.sql, src/main/resources/mybatis.mappers/coffeeMapper.xml
- 톰캣 구동시 CoffeeMapper에서 매핑시에 발생하던 ClassNotFoundException: Cannot find class: coffeeMap 에러를 해결했습니다.
=> :bug: Fix ClassNotFoundException when mapping

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/webapp/WEB-INF/spring/servlet-context.xml, src/main/webapp/WEB-INF/view/index.jsp, src/main/webapp/WEB-INF/view/order/endorder.jsp, src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/manage-order.js, src/main/webapp/assets/js/menu-btn.js
payment페이지를 endorder과 연결하며 로그인한 사용자는 미리 정보가 입력되도록 하였습니다.
또한 이미지가 보이지 않는 오류를 해결하였습니다.
추가적으로 DB에 넣거나 제거하는 등의 기능이 실패하였을 때의 처리를 추가하였습니다.
=> :bug: fix image, link

src/main/java/com/grepp/coffee/app/model/order/OrderRepository.java, src/main/java/com/grepp/coffee/app/model/order/OrderService.java, src/main/java/com/grepp/coffee/app/model/order/mapper/OrderMapper.java, src/main/resources/mybatis.mappers/orderMapper.xml
오늘의 주문, 배송 전 주문, 배송 완료 주문을 세는 코드가 추가되었습니다.
=> ✨ add countOrders query 

src/main/java/com/grepp/coffee/app/model/admin/ManageOrderRepository.java, src/main/webapp/assets/js/manage-order.js, src/main/webapp/assets/js/menu-btn.js
json 파일에서 json 파일의 data를 잘못 받아오던 것을 수정하였습니다.
order_id라고 쓰여진 부분을 order_num으로 수정하였습니다.
=> 🐛 fix delete,update Order / wrong JSON data handling 

src/main/resources/init/data.sql, src/main/webapp/WEB-INF/view/admin/menu-list.jsp, src/main/webapp/WEB-INF/view/admin/menu-regist.jsp, src/main/webapp/WEB-INF/view/include/header.jsp
=> :lipstick: Change UI of 'manage coffee' and 'add coffee'

src/main/resources/mybatis.mappers/coffeeMapper.xml
=> :bug: Fix error when update coffeeImg

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/resources/mybatis.mappers/coffeeMapper.xml, src/main/webapp/WEB-INF/view/admin/menu-list.jsp, src/main/webapp/WEB-INF/view/admin/menu-update.jsp
update를 새롭게 바꾸고 list를 정렬하였습니다.
커피 메뉴 수정이 안되는 문제를 해결하였습니다.
=> 🐛  update.jsp

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/MypageRequest.java
=> 💩 fix Controller for mypage

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/controller/web/admin/payload/DetailOrderRequest.java, src/main/webapp/WEB-INF/view/admin/order-detail.jsp, src/main/webapp/WEB-INF/view/admin/order-list.jsp, src/main/webapp/assets/js/manage-order.js
관리자가 오더 관리를 할 때의 jsp를 수정하였습니다.
js 가 제대로 작동하지 않는 에러를 수정하였습니다.
=> 💄 admin/order.jsp

src/main/webapp/WEB-INF/view/include/header.jsp, src/main/webapp/WEB-INF/view/member/signin.jsp
Update: Update Login and header
Update: Update Login and header
로그인과 헤더 바뀐 부분을 확인해주세요
=> :lipstick: Update: Update Login and header

src/main/java/com/grepp/coffee/app/controller/web/member/MemberController.java, src/main/java/com/grepp/coffee/app/controller/web/member/payload/UpdateAddressRequest.java, src/main/java/com/grepp/coffee/app/model/member/MemberRepository.java, src/main/java/com/grepp/coffee/app/model/member/MemberService.java, src/main/java/com/grepp/coffee/app/model/member/mapper/MemberMapper.java, src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/resources/mybatis.mappers/memberMapper.xml, src/main/webapp/WEB-INF/view/member/mypage.jsp, src/main/webapp/WEB-INF/view/member/update-address.jsp
:lipstick: Change UI of update address
=> :lipstick: Change UI of update address

src/main/resources/init/data.sql
fix: fix validation error
우편 번호 검증에서 오류가 나던 부분을 수정하였습니다.
다른 부분도 찾아보겠습니다.
=> :bug: fix: fix validation error

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/webapp/WEB-INF/view/admin/order-detail.jsp, src/main/webapp/WEB-INF/view/admin/order-list.jsp
- 마지막 주문을 조회할때 IndexOutBound 예외가 발생하는 문제를 처리했습니다.
=> :bug: Fix error on get order by admin

src/main/webapp/WEB-INF/view/member/mypage.jsp
fix: Update mypage.jsp
fix: Update mypage.jsp
=> :lipstick: fix: Update mypage.jsp

src/main/java/com/grepp/coffee/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeRepository.java, src/main/java/com/grepp/coffee/app/model/coffee/CoffeeService.java
- 이미지가 없던 메뉴에 이미지를 삽입할때 삽입되지 않는 문제를 해결했습니다.
=> :bug: Fix error on update menu image

src/main/webapp/WEB-INF/view/admin/adminpage.jsp, src/main/webapp/WEB-INF/view/member/guest.jsp
=> :lipstick: change non-member search order page

src/main/java/com/grepp/coffee/infra/config/SecurityConfig.java, src/main/webapp/WEB-INF/view/member/guest.jsp
=> 🐛 fix delete btn in guest.jsp

src/main/webapp/WEB-INF/view/include/header.jsp, src/main/webapp/WEB-INF/view/index.jsp, src/main/webapp/WEB-INF/view/order/order.jsp
=> :lipstick: change shopping cart UI

src/main/java/com/grepp/coffee/app/controller/api/order/OrderApiController.java, src/main/java/com/grepp/coffee/app/controller/web/order/OrderController.java, src/main/webapp/WEB-INF/view/index.jsp, src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/count.js
=> 🐛 fix stock error

src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/count.js
=> :lipstick: update order.jsp

src/main/webapp/WEB-INF/view/order/order.jsp, src/main/webapp/assets/js/count.js
=> Semi Final Result

src/main/webapp/WEB-INF/view/include/header.jsp
=> :bug: fix admin home

src/main/webapp/WEB-INF/view/member/guest.jsp
=> :bug: fix img url error
